title: "Tech Notes"
description: "Cloud & Architecture notes"
baseurl: ""
url: "https://xii-ray.github.io"

remote_theme: "pages-themes/hacker"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache



